id: P6DC00F9D
initial_creation_type: input
source_metadata:
  title: Pewar Rinpoche
  language: bo
  description: 'Texts by and about Pewar Rinpoche Chime Dorje (dpe war ''chi med rdo
    rje, b. 1933), a major contributor to the recent resurgence of Buddhism in Tibet:'
  volume:
    5c03360201e14518ba5dd9680f46019c:
      title: Prayer for the Long Life of Pewar Rinpoche
      parent: Long Life Prayers
created_at: '2022-03-01T01:17:56.078547'
last_modified_at: '2022-03-01T01:17:56.078550'
statistics:
  total_words: 101
  total_non_words: 8
quality:
  non_words_ratio: 0.08
